### ISSUE TITLE
tevatron.retriever.dataset unfound

### ISSUE THREAD

**Issue by zmingzhang** [ielab/PromptReps#2]
tevatron.retriever.dataset unfound in tevatron files，may other version？

Traceback (most recent call last):
  File "/workspace/projects/PromptReps-main/encode.py", line 17, in <module>
    from dataset import PromptRepsEncodeDataset, PromptRepsEncodeCollator
  File "/workspace/projects/PromptReps-main/dataset.py", line 3, in <module>
    from tevatron.retriever.dataset import EncodeDataset, TrainDataset
ModuleNotFoundError: No module named 'tevatron.retriever'

**Comment by ArvinZhuang** [comment]
hi @IIEzhangzm 
How did you install the tevatron? you should install it from the source by cloning the latest repo ([tevatron v2](https://github.com/texttron/tevatron)).
